### ISSUE TITLE
Prerequisites - sudo: apt: command not found

### ISSUE THREAD

**Issue by RejAnd** [michaelroland/wdnas-dl2100-kernel#3]
If i want to run the command "sudo apt install build-essential fakeroot libncurses5-dev" directly on the dl2100 device, i got this message: "sudo: apt: command not found"

**Comment by michaelroland** [comment]
Did you install Debian onto your NAS before trying that command?

**Comment by RejAnd** [comment]
Maybe I'm getting something wrong. I thought I had to execute the commands to build the kernel before updating the DEbian kernel. 
But no, I didn't install DEbian before. I tried to meet the requirements first.

**Comment by michaelroland** [comment]
The *Getting Started* clearly states

> All scripts are designed to be run on Debian 9 (stretch) either directly on the DL2100 or on any other amd64 (x64, x86-64) architecture. The scripts will probably run on other Debian and Ubuntu versions too. Currently, no effort was taken towards cross-compilation. Hence, the requirement to build on an amd64 architecture, which matches the processor architecture of the DL2100.

You need to get your Debian setup first (either on the NAS or on another x86-64 machine) and do compilation there. Btw. the NAS will run fine (more or less) with the kernel that ships precompiled with Debian, so you can install Debian on the NAS first and then compile the customized kernel there.
